import Language from '@/components/molecules/Language';
import Box from '@/components/organisms/Box';
import Header from '@/components/organisms/Header';
import { Inter } from '@next/font/google';
import Head from 'next/head';
const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>JR Translator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="py-8 px-5 lg:px-52">
        <div className="translation-wrapper lg:grid lg:grid-cols-2">
          <div className="lg:order-2">
            <Box isInput={true} />
          </div>
          <div className="lg:order-1 lg:col-span-2">
            <Language />
          </div>
          <div className="lg:order-3">
            <Box isInput={false} />
          </div>
        </div>
      </main>
    </>
  );
}
